apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitness-service
  template:
    metadata:
      labels:
        app: fitness-service
    spec:
      containers:
        - name: fitness-service
          image: your-dockerhub-username/fitness-service
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: fitness-service
spec:
  selector:
    app: fitness-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
