name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and Test Auth Service
        run: |
          cd auth-service
          mvn -B clean install
          mvn test

      - name: Verify Auth Service JAR exists
        run: |
          ls -la auth-service/target

      - name: Build and Test Fitness Service
        run: |
          cd fitness-service
          mvn -B clean install
          mvn test

      - name: Verify Fitness Service JAR exists
        run: |
          ls -la fitness-service/target

      - name: Build Docker image for auth-service
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service ./auth-service

      - name: Build Docker image for fitness-service
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fitness-service ./fitness-service

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image for auth-service
        run: docker push ${{ secrets.DOCKER_USERNAME }}/auth-service

      - name: Push Docker image for fitness-service
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fitness-service

#      - name: Install Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '20'
#
#      - name: Build Frontend
#        run: |
#          cd frontend
#          npm install
#          npm run build
#
#      - name: Deploy Frontend to GitHub Pages
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./frontend/build

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.18.0'

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./k8s/auth-service.yaml
          kubectl apply -f ./k8s/fitness-service.yaml
